---
apiVersion: v1
kind: Service
metadata:
  name: mod2-svc
  annotations:
    "mc-router.itzg.me/externalServerName": "mod.kigawa.net"
spec:
  selector:
    app: mod
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      name: mc
  type: ClusterIP