---
apiVersion: v1
kind: Service
metadata:
  name: lunail-mod-svc
  annotations:
    "mc-router.itzg.me/externalServerName": "mod2.kigawa.net"
spec:
  selector:
    app: lunail-mod
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      name: mc
  type: ClusterIP