
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kigawa-net-kizuna-pv-1
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 64Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user
      namespace: rook-ceph
    volumeAttributes:
      "clusterID": "rook-ceph"
      "fsName": "rook-cephfs"
      "staticVolume": "true"
      "rootPath": "/org/kigawa-net/kizuna"
    volumeHandle: kigawa-net-kizuna-pv
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
