
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kizuana-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
  volumeName: kigawa-net-kizuna-pv
